# Generated by Django 5.2.6 on 2025-12-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom technique du champ (ex: full_name)",
                        max_length=100,
                        verbose_name="Nom du champ",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label affiché à l'utilisateur",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("email", "Email"),
                            ("tel", "Téléphone"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Type de champ",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Placeholder"
                    ),
                ),
                ("required", models.BooleanField(default=False, verbose_name="Requis")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Pour select/radio (ex: ['Option 1', 'Option 2'])",
                        null=True,
                        verbose_name="Options",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_form_fields",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ de formulaire",
                "verbose_name_plural": "Champs de formulaire",
                "db_table": "contact_form_fields",
                "ordering": ["order", "created_at"],
                "unique_together": {("website", "name")},
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_data", models.JSONField(verbose_name="Données du formulaire")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Nom"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=255, verbose_name="Sujet"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("read", "Lu"),
                            ("replied", "Répondu"),
                            ("archived", "Archivé"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Répondu le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_messages",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "db_table": "contact_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contact_mes_status_060932_idx",
                    ),
                    models.Index(fields=["email"], name="contact_mes_email_a7fb56_idx"),
                ],
            },
        ),
    ]
