# Generated by Django 5.2.6 on 2025-12-05 13:35

import django.db.models.deletion
import websites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom du site")),
                (
                    "domain",
                    models.CharField(
                        help_text="Ex: example.com",
                        max_length=255,
                        verbose_name="Domaine",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "api_key",
                    models.CharField(
                        default=websites.models.generate_api_key,
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Clé API",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "allowed_origins",
                    models.TextField(
                        blank=True,
                        help_text="Une origine par ligne. Ex: https://example.com",
                        verbose_name="Origines autorisées (CORS)",
                    ),
                ),
                (
                    "total_contacts",
                    models.IntegerField(
                        default=0, verbose_name="Total de contacts reçus"
                    ),
                ),
                (
                    "total_projects",
                    models.IntegerField(default=0, verbose_name="Total de projets"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site web",
                "verbose_name_plural": "Sites web",
                "db_table": "websites",
                "ordering": ["-created_at"],
                "unique_together": {("user", "domain")},
            },
        ),
    ]
