# Generated by Django 5.2.6 on 2025-12-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du webhook"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL qui recevra les données du webhook",
                        verbose_name="URL de callback",
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        help_text="Liste des événements qui déclencheront ce webhook",
                        verbose_name="Événements à surveiller",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret pour signer les requêtes webhook (HMAC)",
                        max_length=100,
                        verbose_name="Secret",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "retry_on_failure",
                    models.BooleanField(
                        default=True, verbose_name="Réessayer en cas d'échec"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, verbose_name="Nombre maximum de tentatives"
                    ),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True,
                        help_text="Headers HTTP additionnels à envoyer",
                        null=True,
                        verbose_name="Headers personnalisés",
                    ),
                ),
                (
                    "total_calls",
                    models.IntegerField(default=0, verbose_name="Total d'appels"),
                ),
                (
                    "successful_calls",
                    models.IntegerField(default=0, verbose_name="Appels réussis"),
                ),
                (
                    "failed_calls",
                    models.IntegerField(default=0, verbose_name="Appels échoués"),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier déclenchement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Type d'événement"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Succès"),
                            ("failed", "Échoué"),
                            ("retrying", "Nouvelle tentative"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Données envoyées")),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Code de statut HTTP"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Corps de la réponse"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "attempt_number",
                    models.IntegerField(default=1, verbose_name="Numéro de tentative"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée (ms)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="webhooks.webhook",
                        verbose_name="Webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de webhook",
                "verbose_name_plural": "Logs de webhooks",
                "db_table": "webhook_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "status", "-created_at"],
                        name="webhook_log_webhook_872981_idx",
                    )
                ],
            },
        ),
    ]
