# Generated by Django 5.2.6 on 2025-12-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=100, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_categories",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "db_table": "project_categories",
                "ordering": ["order", "name"],
                "unique_together": {("website", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Contenu détaillé"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/thumbnails/%Y/%m/",
                        verbose_name="Image miniature",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/images/%Y/%m/",
                        verbose_name="Image principale",
                    ),
                ),
                ("demo_url", models.URLField(blank=True, verbose_name="URL de démo")),
                ("github_url", models.URLField(blank=True, verbose_name="URL GitHub")),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="URL externe"),
                ),
                (
                    "technologies",
                    models.JSONField(
                        blank=True,
                        help_text="Ex: ['Python', 'Django', 'React']",
                        null=True,
                        verbose_name="Technologies",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Champs personnalisés"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Projet vedette"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Nombre de vues"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publié le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.category",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "db_table": "projects",
                "ordering": ["-order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/gallery/%Y/%m/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Légende"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de projet",
                "verbose_name_plural": "Images de projet",
                "db_table": "project_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                ("slug", models.SlugField(blank=True, verbose_name="Slug")),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Code hexadécimal (ex: #3B82F6)",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_tags",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "project_tags",
                "ordering": ["name"],
                "unique_together": {("website", "slug")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="projects.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "-published_at"], name="projects_status_01ed1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_featured", "-order"], name="projects_is_feat_da7362_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("website", "slug")},
        ),
    ]
