# Generated by Django 5.2.6 on 2025-12-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("contact_received", "Contact reçu"),
                            ("contact_read", "Contact lu"),
                            ("contact_replied", "Contact répondu"),
                            ("project_viewed", "Projet consulté"),
                            ("project_created", "Projet créé"),
                            ("project_updated", "Projet mis à jour"),
                            ("api_call", "Appel API"),
                            ("form_submission", "Soumission de formulaire"),
                        ],
                        max_length=50,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Données additionnelles de l'événement",
                        null=True,
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("referer", models.URLField(blank=True, verbose_name="Referer")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Pays (code ISO)"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement Analytics",
                "verbose_name_plural": "Événements Analytics",
                "db_table": "analytics_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["website", "event_type", "-created_at"],
                        name="analytics_e_website_2e91f1_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_e_created_3bce1d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "contacts_count",
                    models.IntegerField(default=0, verbose_name="Nombre de contacts"),
                ),
                (
                    "projects_views",
                    models.IntegerField(default=0, verbose_name="Vues de projets"),
                ),
                (
                    "api_calls",
                    models.IntegerField(default=0, verbose_name="Appels API"),
                ),
                (
                    "unique_visitors",
                    models.IntegerField(default=0, verbose_name="Visiteurs uniques"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="websites.website",
                        verbose_name="Site web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques journalières",
                "verbose_name_plural": "Statistiques journalières",
                "db_table": "daily_stats",
                "ordering": ["-date"],
                "unique_together": {("website", "date")},
            },
        ),
    ]
