# Generated by Django 5.2.6 on 2025-12-05 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("agency", "Agency"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Période de facturation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "websites_limit",
                    models.IntegerField(
                        default=1,
                        help_text="-1 pour illimité",
                        verbose_name="Limite de sites web",
                    ),
                ),
                (
                    "contacts_per_month",
                    models.IntegerField(
                        default=50, verbose_name="Messages de contact par mois"
                    ),
                ),
                (
                    "projects_limit",
                    models.IntegerField(
                        default=5,
                        help_text="-1 pour illimité",
                        verbose_name="Limite de projets",
                    ),
                ),
                (
                    "storage_mb",
                    models.IntegerField(default=100, verbose_name="Stockage en MB"),
                ),
                (
                    "analytics",
                    models.BooleanField(default=False, verbose_name="Analytics activé"),
                ),
                (
                    "integrations",
                    models.BooleanField(
                        default=False, verbose_name="Intégrations activées"
                    ),
                ),
                (
                    "custom_domain",
                    models.BooleanField(
                        default=False, verbose_name="Domaine personnalisé"
                    ),
                ),
                (
                    "white_label",
                    models.BooleanField(default=False, verbose_name="White label"),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, verbose_name="Support prioritaire"
                    ),
                ),
                (
                    "current_month_contacts",
                    models.IntegerField(default=0, verbose_name="Messages du mois"),
                ),
                (
                    "current_storage_mb",
                    models.FloatField(default=0, verbose_name="Stockage utilisé (MB)"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'annulation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
